#
#  ██╗  ██╗ ██╗   ██╗ ██████╗  ██████╗  ██╗       █████╗  ███╗   ██╗ ██████╗       ██████╗  ██████╗  ███╗   ██╗ ███████╗
#  ██║  ██║ ╚██╗ ██╔╝ ██╔══██╗ ██╔══██╗ ██║      ██╔══██╗ ████╗  ██║ ██╔══██╗     ██╔════╝ ██╔═══██╗ ████╗  ██║ ██╔════╝
#  ███████║  ╚████╔╝  ██████╔╝ ██████╔╝ ██║      ███████║ ██╔██╗ ██║ ██║  ██║     ██║      ██║   ██║ ██╔██╗ ██║ █████╗
#  ██╔══██║   ╚██╔╝   ██╔═══╝  ██╔══██╗ ██║      ██╔══██║ ██║╚██╗██║ ██║  ██║     ██║      ██║   ██║ ██║╚██╗██║ ██╔══╝
#  ██║  ██║    ██║    ██║      ██║  ██║ ███████╗ ██║  ██║ ██║ ╚████║ ██████╔╝ ██╗ ╚██████╗ ╚██████╔╝ ██║ ╚████║ ██║
#  ╚═╝  ╚═╝    ╚═╝    ╚═╝      ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝ ╚═╝  ╚═══╝ ╚═════╝  ╚═╝  ╚═════╝  ╚═════╝  ╚═╝  ╚═══╝ ╚═╝
#

# Shared configuration is split using Hyprland's native source directive.
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/machine.conf
